name: RP2040
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          project-type: library
  build:
    name: Test compiling 
    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:mbed_rp2040:pico                 # rpi pico
          
        include:
            
          - arduino-boards-fqbn: arduino:mbed_rp2040:pico # raspberry pi pico - one example
            sketch-names: open_loop_position_example.ino            

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@master
      with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          required-libraries: ${{ matrix.required-libraries }}
          platform-url: ${{ matrix.platform-url }}
          sketch-names: ${{ matrix.sketch-names }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
          build-properties: ${{ toJson(matrix.build-properties) }}
